name: Vulnerability Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 3 * * 1' # Runs at 03:00 UTC every Monday

jobs:
  vuln:
    name: Run "make vuln"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
        with:
          go-version: '1.25.5'
      - name: Run vulnerability scan
        run: make vuln
