name: Vulnerability Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 3 * * 1' # Runs at 03:00 UTC every Monday

jobs:
  vuln:
    name: Run "make vuln"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # tag=v6.0.0
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # tag=v6.0.0
        with:
          go-version: '1.25.3'
      - name: Run vulnerability scan
        run: make vuln
